# Generated by Django 3.0.6 on 2020-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
