# Generated by Django 4.1.10 on 2023-07-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='id_post',
        ),
    ]
