# Generated by Django 4.1.10 on 2023-07-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_rename_id_post_id_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_post',
            new_name='id',
        ),
    ]
